### ISSUE TITLE
Method GetDownloadURL returns an error (empty host)

### ISSUE THREAD

**Issue by vadimyer** [rylio/ytdl#21]
```
Get http:///yts/jsbin/player-en_GB-vflJIlAsj/base.js: http: no Host in request URL
```

Recently my bot (github.com/vadimyer/RealMusicBot) stopped working for almost all videos because of the error from `GetDownloadURL`.

As it seems it constructs a URL without a host.

**Comment by fent** [comment]
We had a similar error in [ytdl-core](https://github.com/fent/node-ytdl-core/issues/104) a few days ago.

A good solution is to use [ResolveReference](https://golang.org/pkg/net/url/#example_URL_ResolveReference), rather than prepending "http:" on [this line](https://github.com/rylio/ytdl/blob/master/signature.go#L118)

**Comment by rylio** [comment]
@fent Thanks for the tip!
